### ISSUE TITLE
Better description of JSON formatting required for Config.json

### ISSUE THREAD

**Issue by TanukiKabuki** [maxisoft/ASFFreeGames#84]
For each of the configurable options for ASFFreeGames, it mentions configuring rules within the config.json, however each time I attempt to do so, it states the format is in correct. After several attempts to configure the NoF2P rules I met with no message of error, but also no confirmation of success.
It would be nice to have a formatting example for the file or some level of feedback in the cli readout of ASF.

**Comment by maxisoft** [comment]
Hey there,

Thanks for reporting this issue! It seems there's a compatibility problem between ASF-FreeGames and recent ASF versions.

I've identified the root cause as a change in `System.Text.Json` ASF's serialization behavior, which is preventing the plugin from correctly loading the config json file.
```
2024-08-08 13:36:48|ArchiSteamFarm-1176|ERROR|ASF|Execute() System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
```

I'm currently working on a fix to address this issue. In the meantime, please be aware that the plugin might not function as expected.

I apologize for any inconvenience this may cause and appreciate your patience.

I'll provide an update as soon as possible.

Best,

**Comment by TanukiKabuki** [comment]
No worries, I was under the impression that I was doing something incorrectly and so I was like, well maybe this should be a feature request since its me just not understanding the formatting required. Good to know its not just me!

**Comment by TanukiKabuki** [comment]
Perfect tracking your changes now, thanks for the work! Can I buy you a coffee?
